import sys
import math
import numpy as np

EPSILON = sys.float_info.epsilon
GRAVITY = 20.0
BOUND_BOX_OFFSET = 0.1

CHECK_COLLIDE_HEIGHT_MAP_LEVEL = 2

# Player
ACCELERATION = 2.0
FORWARD_MOVE_SPEED = 15.0
AIM_ANGLE_THRESHOLD = 0.08

SIDE_ACCELERATION = 8.0
SIDE_MOVE_SPEED = 15.0

VERTICAL_ACCELERATION = 8.0
VERTICAL_MOVE_SPEED = 15.0

ROTATION_PITCH_LIMIT = math.pi * 0.3
ROTATION_ROLL_LIMIT = math.pi * 0.25
ROTATION_SPEED = 2.0
ROTATION_ROLL_SPEED = 1.0

TOP_POSITION_LIMIT = 50.0
BOTTOM_POSITION_LIMIT = -50.0
DAMPING_HEIGHT = 5.0
DAMPING_RATIO = min(1.0, max(0.0, DAMPING_HEIGHT / (TOP_POSITION_LIMIT - BOTTOM_POSITION_LIMIT)))

# Camera
ROTATION_DELAY_SPEED = 2.0
ROTATION_DELAY_LIMIT = 0.25
CAMERA_OFFSET_HORIZONTAL = 8.0
CAMERA_OFFSET_VERTICAL = 8.0
CAMERA_OFFSET_SPEED = 5.0
CAMERA_OFFSET_Y = 4.0

# UI
AIM_DISTANCE = 100000.0
ZOOM_SPEED = 5.0

# Resources
SOUND_EXPLOSION = 'explode_02'
SOUND_FIRE = 'assaultrifle1'
SOUND_BULLET_HITS = ['Bullet_Metal_01', 'Bullet_Metal_02', 'Bullet_Metal_03']
SOUND_BGM = 'game_load'
SOUND_BEEP_WANING = 'beep_warning'
