import sys
import math
import numpy as np

EPSILON = sys.float_info.epsilon
GRAVITY = 20.0
BOUND_BOX_OFFSET = 0.1

# Player
ACCELERATION = 1.0
FORWARD_MOVE_SPEED = 10.0
AIM_ANGLE_THRESHOLD = 0.08

SIDE_ACCELERATION = 4.0
SIDE_MOVE_SPEED = 10.0

ROTATION_PITCH_LIMIT = min(0.5, math.pi * 0.5)
ROTATION_ROLL_LIMIT = min(0.5, math.pi * 0.5)
ROTATION_SPEED = 2.0
ROTATION_ROLL_SPEED = 1.0

# Camera
ROTATION_DELAY_SPEED = 2.0
ROTATION_DELAY_LIMIT = 0.25
CAMERA_OFFSET_HORIZONTAL = 8.0
CAMERA_OFFSET_VERTICAL = 8.0
CAMERA_OFFSET_SPEED = 5.0
CAMERA_OFFSET_Y = 4.0

# UI
AIM_DISTANCE = 100000.0
ZOOM_SPEED = 5.0
